Repository ament/ament_package, pull requests merged in 2019-10, with the labels that each got.

#90 add quotes around ament_python_executable variable in local_setup.bat
  ament_package/template/isolated_prefix_level/local_setup.bat.in
  ament_package/template/prefix_level/local_setup.bat.in
Labels: bug, in review

#89 perform environment calculation in Python
  ament_package/template/prefix_level/_local_setup_util.py
  ament_package/template/prefix_level/_order_packages.py
  ament_package/template/prefix_level/local_setup.bat.in
  ament_package/template/prefix_level/local_setup.sh.in
  ament_package/template/prefix_level/local_setup.zsh
  ament_package/templates.py
Labels: enhancement, in review

#92 if no package.dsv is available fallback to a local_setup file
  ament_package/template/prefix_level/_local_setup_util.py
Labels: bug

#93 fix reading the package run dependencies
  ament_package/template/prefix_level/_local_setup_util.py
Labels: bug, in review

#94 provide ament_prepend_unique_value function in prefix level sh script
  ament_package/template/prefix_level/local_setup.sh.in
Labels: bug, in review

#96 keep using default ignore list
  .flake8
Labels: bug, in review

#95 add type 'set' for dsv files
  ament_package/template/prefix_level/_local_setup_util.py
Labels: enhancement, in review

#99 [backport dashing] install resource marker file for package
  resource/ament_package
  setup.py
Labels: in review

#100 [backport dashing] add quotes around ament_python_executable variable in local_setup.bat
  ament_package/template/isolated_prefix_level/local_setup.bat.in
  ament_package/template/prefix_level/local_setup.bat.in
Labels: in review

#101 Add support for prepending multiple values to env variables from .dsv files
  ament_package/template/prefix_level/_local_setup_util.py
Labels: enhancement, in review

#102 add dsv type set-if-unset
  ament_package/template/prefix_level/_local_setup_util.py
Labels: enhancement, in review
